# Generated by Django 5.1.2 on 2025-09-12 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_topic_topicrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loginentry',
            old_name='timestamp',
            new_name='login_time',
        ),
        migrations.RemoveField(
            model_name='loginentry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='loginentry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='loginentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topicrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='loginentry',
            name='username',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='consumption',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_produced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='observers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='production',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topicrequest',
            name='partitions',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='topicrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
